// Code generated by "stringer -type=Piece"; DO NOT EDIT

package main

import "fmt"

const _Piece_name = "NonePawnKnightBishopRookQueenKingAll"

var _Piece_index = [...]uint8{0, 4, 8, 14, 20, 24, 29, 33, 36}

func (i Piece) String() string {
	if i >= Piece(len(_Piece_index)-1) {
		return fmt.Sprintf("Piece(%d)", i)
	}
	return _Piece_name[_Piece_index[i]:_Piece_index[i+1]]
}
